### Passo 01
 - importe das bibliotecas
 - carrega conjunto de dados

### Bibliotecas e conjunto de dados

Este bloco importa as ferramentas de aprendizado de máquina e carrega o conjunto Iris, que contém medidas de flores e rótulos de três espécies.

In [1]:
import tensorflow as tf
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Carregar conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

### Passo 02
 - pré-processamento dos dados
 - divisão do conjunto em treinamento e testes
 - normaliza os dados

### Separação e normalização dos dados

Os dados são divididos em conjuntos de treino e teste para avaliar o modelo em exemplos que não foram usados no aprendizado. O `StandardScaler` padroniza as medidas; ele é ajustado somente com os dados de treino.

In [2]:
# Dividir o conjunto de dados em treinamento e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados para otimizar o treinamento da rede neural
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Passo 03
 - construir o modelo
 - uma rede neural simples

### Arquitetura da rede neural

O modelo sequencial contém uma camada oculta com ativação ReLU e uma camada de saída softmax com três classes, uma para cada espécie Iris.

In [3]:
# Rede neural simples com uma camada oculta densa
modelo = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(3, activation='softmax') # 3 classes de saída para as espécies Iris
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Passo 04
 - treino do modelo

### Configuração e treinamento

O modelo usa o otimizador Adam, uma função de perda adequada a rótulos inteiros e a métrica de acurácia. Em seguida, aprende padrões a partir dos dados de treino.

In [4]:
# Treinar o Modelo
modelo.compile(optimizer='adam',
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

# Treinamento com os dados de treino
print("Iniciando o treinamento do modelo...")
historico = modelo.fit(X_train, y_train, epochs=50, verbose=0)
print("Treinamento concluído.")

Iniciando o treinamento do modelo...
Treinamento concluído.


### Passo 05
 - avaliação

### Avaliação no conjunto de teste

Esta etapa mede a perda e a acurácia usando os dados separados para teste. Essas métricas dão uma indicação de como o modelo classifica exemplos não vistos durante o treinamento.

In [5]:
# Avaliar o Modelo
perda, precisao = modelo.evaluate(X_test, y_test, verbose=0)
print(f"\nPrecisão alcançada nos dados de teste: {precisao:.4f}")


Precisão alcançada nos dados de teste: 0.7333


### Passo 06
 - previsões

### Previsões e interpretação

O modelo calcula probabilidades para as classes, e `argmax` seleciona a classe com maior valor. As previsões são comparadas com os rótulos reais e, quando disponível, exibidas com os nomes das espécies.

In [6]:
# Fazer Previsões
previsoes = modelo.predict(X_test)
classes_previstas = np.argmax(previsoes, axis=1)
print("\nAlgumas previsões realizadas (Classes previstas vs Reais):")
for i in range(5):
    print(f"Previsto: {classes_previstas[i]} | Real: {y_test[i]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Algumas previsões realizadas (Classes previstas vs Reais):
Previsto: 1 | Real: 1
Previsto: 0 | Real: 0
Previsto: 2 | Real: 2
Previsto: 2 | Real: 1
Previsto: 2 | Real: 1


Esta célula está reservada para anotações ou execução complementar.

Esta célula está reservada para anotações ou execução complementar.

### Bibliotecas e conjunto de dados

Este bloco importa as ferramentas de aprendizado de máquina e carrega o conjunto Iris, que contém medidas de flores e rótulos de três espécies.

In [7]:
# Passo 1: Importar bibliotecas
import tensorflow as tf
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Fixar semente aleatória para reprodutibilidade dos resultados
tf.random.set_seed(42)
np.random.seed(42)

# Carregar conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

# Passo 2: Pré-processamento dos Dados
# Dividir o conjunto de dados em treinamento e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados para otimizar o treinamento da rede neural
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Passo 3: Construir o Modelo
# Rede neural simples com uma camada oculta densa
modelo = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(3, activation='softmax')  # 3 classes de saída para as espécies Iris
])

# Passo 4: Treinar o Modelo
modelo.compile(optimizer='adam',
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

# Treinamento com os dados de treino
print("Iniciando o treinamento do modelo...")
historico = modelo.fit(X_train, y_train, epochs=50, verbose=0)
print("Treinamento concluído.")

# Passo 5: Avaliar o Modelo
perda, precisao = modelo.evaluate(X_test, y_test, verbose=0)
print(f"\nPrecisão alcançada nos dados de teste: {precisao:.4f}")

# Passo 6: Fazer Previsões
previsoes = modelo.predict(X_test, verbose=0)
classes_previstas = np.argmax(previsoes, axis=1)
print("\nAlgumas previsões realizadas (Classes previstas vs Reais):")
for i in range(5):
    print(f"Previsto: {classes_previstas[i]} | Real: {y_test[i]}")

# Nomes das espécies, para leitura mais clara das previsões
nomes_especies = iris.target_names
print("\nAlgumas previsões com nomes das espécies:")
for i in range(5):
    print(f"Previsto: {nomes_especies[classes_previstas[i]]:<10} | Real: {nomes_especies[y_test[i]]}")

# Avaliação complementar: matriz de confusão e relatório de classificação
from sklearn.metrics import confusion_matrix, classification_report

matriz_confusao = confusion_matrix(y_test, classes_previstas)
print("\nMatriz de Confusão:")
print(matriz_confusao)

print("\nRelatório de Classificação:")
print(classification_report(y_test, classes_previstas, target_names=nomes_especies))

# Salvando artefatos para os gráficos do relatório
import json
with open('historico_treino.json', 'w') as f:
    json.dump(historico.history, f)
np.save('matriz_confusao.npy', matriz_confusao)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Iniciando o treinamento do modelo...
Treinamento concluído.

Precisão alcançada nos dados de teste: 0.9000

Algumas previsões realizadas (Classes previstas vs Reais):
Previsto: 1 | Real: 1
Previsto: 0 | Real: 0
Previsto: 2 | Real: 2
Previsto: 2 | Real: 1
Previsto: 2 | Real: 1

Algumas previsões com nomes das espécies:
Previsto: versicolor | Real: versicolor
Previsto: setosa     | Real: setosa
Previsto: virginica  | Real: virginica
Previsto: virginica  | Real: versicolor
Previsto: virginica  | Real: versicolor

Matriz de Confusão:
[[10  0  0]
 [ 0  6  3]
 [ 0  0 11]]

Relatório de Classificação:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.67      0.80         9
   virginica       0.79      1.00      0.88        11

    accuracy                           0.90        30
   macro avg       0.93      0.89      0.89        30
weighted avg       0.92      0.90      0.90        30

